# University Policy Knowledge Based System

### 1. Create the Knowledge Base Database

Table 1. Debate Arguments

In [ ]:
debate <- data.frame(
  Argument_ID = c("A001","A002","A003","A004","A005","A006"),
  Position = c("For","For","For","Against","Against","Against"),
  Topic = c("Learning","Productivity","AI Literacy",
            "Academic Integrity","Dependency","Assessment"),
  Claim = c(
    "AI can provide students with immediate learning support.",
    "AI can help student complete routine academic tasks more efficiently.",
    "Allowing AI use can helps students develop AI literacy.",
    "Undisclosed AI-generated work may create academic integrity concerns.",
    "Excessive AI use may reduce students' independent problem-solving practice.",
    "AI use may make it more difficult to determine whether submitted work reflects student learning."
  )
)

debate

  Argument_ID Position Topic
1 A001        For      Learning
2 A002        For      Productivity
3 A003        For      AI Literacy
4 A004        Against  Academic Integrity
5 A005        Against  Dependency
6 A006        Against  Assessment
  Claim
1 AI can provide students with immediate learning support.
2 AI can help student complete routine academic tasks more efficiently.
3 Allowing AI use can helps students develop AI literacy.
4 Undisclosed AI-generated work may create academic integrity concerns.
5 Excessive AI use may reduce students' independent problem-solving practice.
6 AI use may make it more difficult to determine whether submitted work reflects student learning.

Table 2. Evidence

In [ ]:
evidence <- data.frame(
  Evidence_ID = c("E001", "E002", "E003", "E004", "E005", "E006"),
  Argument_ID = c("A001", "A002", "A003", "A004", "A005", "A006"),
  Evidence_Type = c("Research", "Research", "Policy", "Policy", "Research", "Research"),
  Strength = c("Strong", "Moderate", "Strong", "Strong", "Moderate", "Strong")
)

evidence

  Evidence_ID Argument_ID Evidence_Type Strength
1 E001        A001        Research      Strong
2 E002        A002        Research      Moderate
3 E003        A003        Policy        Strong
4 E004        A004        Policy        Strong
5 E005        A005        Research      Moderate
6 E006        A006        Research      Strong

### 2. Count the Arguments

In [ ]:
table(debate$Position)

Against     For
      3       3

In [ ]:
table(evidence$Strength)

Moderate   Strong
       2        4

### 3. Retrieve Arguments Supporting Policy

In [ ]:
for_arguments <- subset(
  debate,
  Position == "For"
)

print(for_arguments)

  Argument_ID Position        Topic
1        A001      For     Learning
2        A002      For Productivity
3        A003      For  AI Literacy
                                                                  Claim
1              AI can provide students with immediate learning support.
2 AI can help student complete routine academic tasks more efficiently.
3               Allowing AI use can helps students develop AI literacy.

### 4. Retrieve Arguments Against the Policy

In [ ]:
for_arguments <- subset(
  debate,
  Position == "Against"
)

print(for_arguments)

  Argument_ID Position              Topic
4        A004  Against Academic Integrity
5        A005  Against         Dependency
6        A006  Against         Assessment
                                                                                             Claim
4                            Undisclosed AI-generated work may create academic integrity concerns.
5                      Excessive AI use may reduce students' independent problem-solving practice.
6 AI use may make it more difficult to determine whether submitted work reflects student learning.

### 5. Connect Arguments and Evidence

In [ ]:
knowledge_base <- merge(
  debate,
  evidence,
  by = "Argument_ID"
)
print(knowledge_base)

  Argument_ID Position              Topic
1        A001      For           Learning
2        A002      For       Productivity
3        A003      For        AI Literacy
4        A004  Against Academic Integrity
5        A005  Against         Dependency
6        A006  Against         Assessment
                                                                                             Claim
1                                         AI can provide students with immediate learning support.
2                            AI can help student complete routine academic tasks more efficiently.
3                                          Allowing AI use can helps students develop AI literacy.
4                            Undisclosed AI-generated work may create academic integrity concerns.
5                      Excessive AI use may reduce students' independent problem-solving practice.
6 AI use may make it more difficult to determine whether submitted work reflects student learning.
  Evidence_ID Evidence_Type Strength
1        E001      Research   Strong
2        E002      Research Moderate
3        E003        Policy   Strong
4        E004        Policy   Strong
5        E005      Research Moderate
6        E006      Research   Strong

### 6. Convert Evidence Strength into a Score

In [ ]:
get_score <- function(strength){
  if (strength == "Strong"){
    return(3)
  } else if (strength == "Moderate"){
    return(2)
  } else if (strength == "Weak"){
    return(1)
  } else{
    return(0)
  }
}

get_score("Strong")

[1] 3

### 7. Add Evidence Scores

In [ ]:
knowledge_base$Evidence_Score <- sapply(
  knowledge_base$Strength,
  get_score
)

print(knowledge_base)

  Argument_ID Position              Topic
1        A001      For           Learning
2        A002      For       Productivity
3        A003      For        AI Literacy
4        A004  Against Academic Integrity
5        A005  Against         Dependency
6        A006  Against         Assessment
                                                                                             Claim
1                                         AI can provide students with immediate learning support.
2                            AI can help student complete routine academic tasks more efficiently.
3                                          Allowing AI use can helps students develop AI literacy.
4                            Undisclosed AI-generated work may create academic integrity concerns.
5                      Excessive AI use may reduce students' independent problem-solving practice.
6 AI use may make it more difficult to determine whether submitted work reflects student learning.
  Evidence_ID Evidence_Type Strength Evidence_Score
1        E001      Research   Strong              3
2        E002      Research Moderate              2
3        E003        Policy   Strong              3
4        E004        Policy   Strong              3
5        E005      Research Moderate              2
6        E006      Research   Strong              3

### 8. Classify Evidence Support

In [ ]:
classify_support <- function(score){

  if (score == 3){
    return("Strongly Supported")
  } else if (score == 2){
    return("Moderately Supported")
  } else if (score == 1){
    return("Weakly Supported")
  } else{
    return("No Support")
  }
}

classify_support(2)

[1] "Moderately Supported"

### 9. Search by Topic

In [ ]:
search_topic<- function(topic){
  result <- subset(
  knowledge_base,
  Topic == topic
  )

  if(nrow(result) == 0)(
    cat("Topic not found.\n")
  )else(
    print(result)
  )
}